In [5]:
from google.colab import files
import pandas as pd
import numpy as np
import seaborn as sb
from sklearn.ensemble import GradientBoostingClassifier as GBC
from sklearn.metrics import confusion_matrix as CM
import warnings
warnings.filterwarnings('ignore')

Step 1 Import dataset and do the cleaning

In [ ]:
uploaded = files.upload()
files.upload
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving mnist_test.csv to mnist_test.csv
Saving mnist_train.csv to mnist_train.csv
User uploaded file "mnist_test.csv" with length 18289443 bytes
User uploaded file "mnist_train.csv" with length 109575994 bytes


In [210]:
train = pd.read_csv('mnist_train.csv',header = None)
test = pd.read_csv('mnist_test.csv',header = None)

In [211]:
# Rename the first column as 'initial' to stands for original labels
train.rename(columns={0:'initial'}, inplace=True)
test.rename(columns={0:'initial'}, inplace=True)
print(train)
print(test)

       initial  1  2  3  4  5  6  7  ...  777  778  779  780  781  782  783  784
0            5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
2            4  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
3            1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995        8  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59996        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59997        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59998        6  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59999        8  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[60000 rows x 785 columns]


In [ ]:
train.shape
train.info()

In [ ]:
test.shape
test.info()

In [84]:
train.head(3)

initial  1  2  3  4  5  6  7  8  ...  776  777  778  779  780  781  782  783  784
0        5  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
1        0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
2        4  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0

[3 rows x 785 columns]

In [ ]:
test.head(3)

Step 2 Relabel 10 different digits with integer encoding


In [85]:
######### Model a ########
### train_a
train_a = train
train_a['a_relabel'] = 1
train_a.loc[train_a['initial']==1,'a_relabel']=0
train_a.loc[train_a['initial']==4,'a_relabel']=0 # mark 'relabel' as 0 when initial = 1 and 4
print(train_a)
# print(train_a['relabel'])
### test_a
test_a = test
test_a['a_relabel'] = 1
test_a.loc[test_a['initial']==1,'a_relabel']=0
test_a.loc[test_a['initial']==4,'a_relabel']=0 # mark 'relabel' as 0 when initial = 1 and 4
print(test_a)

       initial  1  2  3  4  5  6  ...  779  780  781  782  783  784  a_relabel
0            5  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
1            0  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
2            4  0  0  0  0  0  0  ...    0    0    0    0    0    0          0
3            1  0  0  0  0  0  0  ...    0    0    0    0    0    0          0
4            9  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
...        ... .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...        ...
59995        8  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
59996        3  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
59997        5  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
59998        6  0  0  0  0  0  0  ...    0    0    0    0    0    0          1
59999        8  0  0  0  0  0  0  ...    0    0    0    0    0    0          1

[60000 rows x 786 columns]
      initial  1  2  3  

In [87]:
### train x
train_a_x = train_a.iloc[:,1:785]
### train y
train_a_y = train_a['a_relabel']
### test_x
test_a_x = test_a.iloc[:,1:785]
### test y
test_a_y = test_a['a_relabel']

In [91]:
clf_a = GBC(random_state=0).fit(train_a_x, train_a_y)
pred_a = clf_a.predict(test_a_x)
print(clf_a.score(test_a_x, test_a_y))

0.9787


In [208]:
print(CM(pred_a,test_a_y))

[[1964   60]
 [ 153 7823]]


In [212]:
######### Model b ########
### train_b
train_b = train
train_b['b_relabel'] = 2
train_b.loc[train_b['initial']==5,'b_relabel']=0
train_b.loc[train_b['initial']==6,'b_relabel']=0 # mark 'relabel' as 0 when initial = 5 and 6
print(train_b)
### test_b
test_b = test
test_b['b_relabel'] = 2
test_b.loc[test_b['initial']==5,'b_relabel']=0
test_b.loc[test_b['initial']==6,'b_relabel']=0 # mark 'relabel' as 0 when initial = 5 and 6
print(test_b)

       initial  1  2  3  4  5  6  ...  779  780  781  782  783  784  b_relabel
0            5  0  0  0  0  0  0  ...    0    0    0    0    0    0          0
1            0  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
2            4  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
3            1  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
4            9  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
...        ... .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...        ...
59995        8  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
59996        3  0  0  0  0  0  0  ...    0    0    0    0    0    0          2
59997        5  0  0  0  0  0  0  ...    0    0    0    0    0    0          0
59998        6  0  0  0  0  0  0  ...    0    0    0    0    0    0          0
59999        8  0  0  0  0  0  0  ...    0    0    0    0    0    0          2

[60000 rows x 786 columns]
      initial  1  2  3  

In [92]:
train_b_x = train_b.iloc[:,1:785]
train_b_y = train_b['b_relabel']
test_b_x = test_b.iloc[:,1:785]
test_b_y = test_b['b_relabel']

In [94]:
clf_b = GBC(random_state=0).fit(train_b_x, train_b_y)
pred_b = clf_b.predict(test_b_x)
print(clf_b.score(test_b_x, test_b_y))

0.9716


In [96]:
print(CM(pred_b,test_b_y))

[[1631   65]
 [ 219 8085]]


In [97]:
######### Model c ########
### train_c
train_c = train
train_c['c_relabel'] = 3
train_c.loc[train_c['initial']==2,'c_relabel']=0 # mark 'relabel' as 0 when initial = 2
print(train_c)
### test_c
test_c = test
test_c['c_relabel'] = 3
test_c.loc[test_c['initial']==2,'c_relabel']=0 # mark 'relabel' as 0 when initial = 2
print(test_c)

       initial  1  2  3  4  5  ...  782  783  784  a_relabel  b_relabel  c_relabel
0            5  0  0  0  0  0  ...    0    0    0          1          0          3
1            0  0  0  0  0  0  ...    0    0    0          1          2          3
2            4  0  0  0  0  0  ...    0    0    0          0          2          3
3            1  0  0  0  0  0  ...    0    0    0          0          2          3
4            9  0  0  0  0  0  ...    0    0    0          1          2          3
...        ... .. .. .. .. ..  ...  ...  ...  ...        ...        ...        ...
59995        8  0  0  0  0  0  ...    0    0    0          1          2          3
59996        3  0  0  0  0  0  ...    0    0    0          1          2          3
59997        5  0  0  0  0  0  ...    0    0    0          1          0          3
59998        6  0  0  0  0  0  ...    0    0    0          1          0          3
59999        8  0  0  0  0  0  ...    0    0    0          1          2          3

[60

In [99]:
train_c_x = train_c.iloc[:,1:785]
train_c_y = train_c['c_relabel']
test_c_x = test_c.iloc[:,1:785]
test_c_y = test_c['c_relabel']

In [124]:
clf_c = GBC(random_state=0).fit(train_c_x, train_c_y)
pred_c = clf_c.predict(test_c_x)
print(clf_c.score(test_c_x, test_c_y))

0.9851


In [126]:
print(CM(pred_c,test_c_y))

[[ 904   21]
 [ 128 8947]]


In [100]:
######### Model d ########
### train_d
train_d = train
train_d['d_relabel'] = 4
train_d.loc[train_d['initial']==1,'d_relabel']=0
train_d.loc[train_d['initial']==4,'d_relabel']=0 # mark 'relabel' as 0 when initial = 1,4,7,9
train_d.loc[train_d['initial']==7,'d_relabel']=0
train_d.loc[train_d['initial']==9,'d_relabel']=0
print(train_d)
### test_d
test_d = test
test_d['d_relabel'] = 4
test_d.loc[test_d['initial']==1,'d_relabel']=0
test_d.loc[test_d['initial']==4,'d_relabel']=0
test_d.loc[test_d['initial']==7,'d_relabel']=0
test_d.loc[test_d['initial']==9,'d_relabel']=0 # mark 'relabel' as 0 when initial = 1,4,7,9
print(test_d)

       initial  1  2  3  4  ...  784  a_relabel  b_relabel  c_relabel  d_relabel
0            5  0  0  0  0  ...    0          1          0          3          4
1            0  0  0  0  0  ...    0          1          2          3          4
2            4  0  0  0  0  ...    0          0          2          3          0
3            1  0  0  0  0  ...    0          0          2          3          0
4            9  0  0  0  0  ...    0          1          2          3          0
...        ... .. .. .. ..  ...  ...        ...        ...        ...        ...
59995        8  0  0  0  0  ...    0          1          2          3          4
59996        3  0  0  0  0  ...    0          1          2          3          4
59997        5  0  0  0  0  ...    0          1          0          3          4
59998        6  0  0  0  0  ...    0          1          0          3          4
59999        8  0  0  0  0  ...    0          1          2          3          4

[60000 rows x 789 columns]


In [127]:
train_d_x = train_d.iloc[:,1:785]
train_d_y = train_d['d_relabel']
test_d_x = test_d.iloc[:,1:785]
test_d_y = test_d['d_relabel']


In [128]:
clf_d = GBC(random_state=0).fit(train_d_x, train_d_y)
pred_d = clf_d.predict(test_d_x)
print(clf_d.score(test_d_x, test_d_y))

0.9723


In [129]:
print(CM(pred_d, test_d_y))

[[4008  131]
 [ 146 5715]]


In [102]:
######### Model e ########
### train_e
train_e = train
train_e['e_relabel'] = 0
train_e.loc[train_e['initial']==0,'e_relabel']=5
train_e.loc[train_e['initial']==2,'e_relabel']=5 # mark 'relabel' as 5 when initial = 1,4,7,9
train_e.loc[train_e['initial']==6,'e_relabel']=5
train_e.loc[train_e['initial']==8,'e_relabel']=5
print(train_e)
### test_e
test_e = test
test_e['e_relabel'] = 0
test_e.loc[test_e['initial']==0,'e_relabel']=5
test_e.loc[test_e['initial']==2,'e_relabel']=5
test_e.loc[test_e['initial']==6,'e_relabel']=5
test_e.loc[test_e['initial']==8,'e_relabel']=5 # mark 'relabel' as 5 when initial = 1,4,7,9
print(test_e)

       initial  1  2  3  ...  b_relabel  c_relabel  d_relabel  e_relabel
0            5  0  0  0  ...          0          3          4          0
1            0  0  0  0  ...          2          3          4          5
2            4  0  0  0  ...          2          3          0          0
3            1  0  0  0  ...          2          3          0          0
4            9  0  0  0  ...          2          3          0          0
...        ... .. .. ..  ...        ...        ...        ...        ...
59995        8  0  0  0  ...          2          3          4          5
59996        3  0  0  0  ...          2          3          4          0
59997        5  0  0  0  ...          0          3          4          0
59998        6  0  0  0  ...          0          3          4          5
59999        8  0  0  0  ...          2          3          4          5

[60000 rows x 790 columns]
      initial  1  2  3  ...  b_relabel  c_relabel  d_relabel  e_relabel
0           7  0  0  0  

In [103]:
train_e_x = train_e.iloc[:,1:785]
train_e_y = train_e['e_relabel']
test_e_x = test_e.iloc[:,1:785]
test_e_y = test_e['e_relabel']

In [130]:
clf_e = GBC(random_state=0).fit(train_e_x, train_e_y)
pred_e = clf_e.predict(test_e_x)
print(clf_e.score(test_e_x, test_e_y))

0.9574


In [131]:
print(CM(pred_e, test_e_y))

[[5845  215]
 [ 211 3729]]


In [104]:
######### Model f ########
### train_f
train_f = train
train_f['f_relabel'] = 6
train_f.loc[train_f['initial']==1,'f_relabel']=0
train_f.loc[train_f['initial']==2,'f_relabel']=0 # mark 'relabel' as 0 when initial = 1,2,3,7
train_f.loc[train_f['initial']==3,'f_relabel']=0
train_f.loc[train_f['initial']==7,'f_relabel']=0
print(train_f)
### test_f
test_f = test
test_f['f_relabel'] = 6
test_f.loc[test_f['initial']==1,'f_relabel']=0
test_f.loc[test_f['initial']==2,'f_relabel']=0
test_f.loc[test_f['initial']==3,'f_relabel']=0
test_f.loc[test_f['initial']==7,'f_relabel']=0 # mark 'relabel' as 0 when initial = 1,2,3,7
print(test_f)

       initial  1  2  3  ...  c_relabel  d_relabel  e_relabel  f_relabel
0            5  0  0  0  ...          3          4          0          6
1            0  0  0  0  ...          3          4          5          6
2            4  0  0  0  ...          3          0          0          6
3            1  0  0  0  ...          3          0          0          0
4            9  0  0  0  ...          3          0          0          6
...        ... .. .. ..  ...        ...        ...        ...        ...
59995        8  0  0  0  ...          3          4          5          6
59996        3  0  0  0  ...          3          4          0          0
59997        5  0  0  0  ...          3          4          0          6
59998        6  0  0  0  ...          3          4          5          6
59999        8  0  0  0  ...          3          4          5          6

[60000 rows x 791 columns]
      initial  1  2  3  ...  c_relabel  d_relabel  e_relabel  f_relabel
0           7  0  0  0  

In [105]:
train_f_x = train_f.iloc[:,1:785]
train_f_y = train_f['f_relabel']
test_f_x = test_f.iloc[:,1:785]
test_f_y = test_f['f_relabel']

In [132]:
clf_f = GBC(random_state=0).fit(train_f_x, train_f_y)
pred_f = clf_f.predict(test_f_x)
print(clf_f.score(test_f_x, test_f_y))

0.9617


In [133]:
print(CM(pred_f, test_f_y))

[[3978  156]
 [ 227 5639]]


In [116]:
######### Model g ########
### train_g
train_g = train
train_g['g_relabel'] = 7
train_g.loc[train_g['initial']==0,'g_relabel']=0
train_g.loc[train_g['initial']==1,'g_relabel']=0 # mark 'relabel' as 0 when initial = 0,1,7
train_g.loc[train_g['initial']==7,'g_relabel']=0
print(train_g)
### test_g
test_g = test
test_g['g_relabel'] = 7
test_g.loc[test_g['initial']==0,'g_relabel']=0
test_g.loc[test_g['initial']==1,'g_relabel']=0 # mark 'relabel' as 0 when initial = 0,1,7
test_g.loc[test_g['initial']==7,'g_relabel']=0
print(test_g)

       initial  1  2  3  ...  d_relabel  e_relabel  f_relabel  g_relabel
0            5  0  0  0  ...          4          0          6          7
1            0  0  0  0  ...          4          5          6          0
2            4  0  0  0  ...          0          0          6          7
3            1  0  0  0  ...          0          0          0          0
4            9  0  0  0  ...          0          0          6          7
...        ... .. .. ..  ...        ...        ...        ...        ...
59995        8  0  0  0  ...          4          5          6          7
59996        3  0  0  0  ...          4          0          0          7
59997        5  0  0  0  ...          4          0          6          7
59998        6  0  0  0  ...          4          5          6          7
59999        8  0  0  0  ...          4          5          6          7

[60000 rows x 792 columns]
      initial  1  2  3  ...  d_relabel  e_relabel  f_relabel  g_relabel
0           7  0  0  0  

In [170]:
train_g_x = train_g.iloc[:,1:785]
train_g_y = train_g['g_relabel']
test_g_x = test_g.iloc[:,1:785]
test_g_y = test_g['g_relabel']

In [171]:
clf_g = GBC(random_state=0).fit(train_g_x, train_g_y)
pred_g = clf_g.predict(test_g_x)
print(clf_g.score(test_g_x, test_g_y))

0.9663


In [172]:
print(CM(pred_g, test_g_y))

[[2924  118]
 [ 219 6739]]


In [199]:
test_relabel = pd.concat(
    [test_g['a_relabel'],test_g['b_relabel'],test_g['c_relabel'],test_g['d_relabel'],
     test_g['e_relabel'],test_g['f_relabel'],test_g['g_relabel']],axis = 0
     )
pred_a = pd.Series(pred_a,dtype = 'uint8')
pred_b = pd.Series(pred_b,dtype = 'uint8')
pred_c = pd.Series(pred_c,dtype = 'uint8')
pred_d = pd.Series(pred_d,dtype = 'uint8')
pred_e = pd.Series(pred_e,dtype = 'uint8')
pred_f = pd.Series(pred_f,dtype = 'uint8')
pred_g = pd.Series(pred_g,dtype = 'uint8')
test_pred = pd.concat([pred_a,pred_b,pred_c,pred_d,pred_e,pred_f,pred_g],axis = 0)
test_relabel
test_pred

0       1
1       1
2       0
3       1
4       0
       ..
9995    7
9996    7
9997    7
9998    7
9999    7
Length: 70000, dtype: uint8

In [207]:
print(CM(test_pred, test_relabel,labels = [0,1,2,3,4,5,6,7]))

[[21254    60    65    21   131   215   156   118]
 [  153  7823     0     0     0     0     0     0]
 [  219     0  8085     0     0     0     0     0]
 [  128     0     0  8947     0     0     0     0]
 [  146     0     0     0  5715     0     0     0]
 [  211     0     0     0     0  3729     0     0]
 [  227     0     0     0     0     0  5639     0]
 [  219     0     0     0     0     0     0  6739]]
0.9704428571428572


In [213]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_pred, test_relabel))

0.9704428571428572
